# Generated by Django 4.0.3 on 2022-05-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attachment',
        ),
    ]
