# Generated by Django 4.0.3 on 2022-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_email_verified_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='Designates whether this user email is verified.Unselect this instead of deleting accounts.', verbose_name='email_verified'),
        ),
    ]
