# Generated by Django 4.0.3 on 2022-04-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_size', models.CharField(choices=[('SINGLE_ROOM', 'Single Room'), ('BEDSITTER', 'Bedsitter'), ('ONE_BEDROOM', 'One Bedroom'), ('TWO_BEDROOM', 'Two Bedroom'), ('THREE_BEDROOM', 'Three Bedroom'), ('FOUR_BEDROOM', 'Four Bedroom'), ('MORE', 'More than 4')], default='ONE_BEDROOM', max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('services', models.JSONField(default=dict)),
                ('quantity', models.IntegerField(default=0)),
                ('service_fee', models.FloatField()),
                ('paid', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INPROGRESS', 'InProgress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='COMPLETE', max_length=100)),
                ('comments', models.TextField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.booking')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
