# Generated by Django 4.0.3 on 2022-05-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_constituency_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
