# Generated by Django 4.0.3 on 2022-05-09 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.constituency')),
            ],
        ),
    ]
