# Generated by Django 4.0.3 on 2022-05-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_booking_express_alter_booking_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='constituency',
            new_name='constituency_name',
        ),
    ]
