# Generated by Django 4.0.3 on 2022-05-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_constituency_ward_constituency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='constituency_name',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='name',
        ),
    ]
