# Generated by Django 4.0.3 on 2022-05-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_ward_constituency_name_remove_ward_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
