# Generated by Django 4.0.3 on 2022-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_booking_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
